title: James Dagenais
author: James Dagenais
email: jcdag333@gmail.com
description: Personal website

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
